# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "peru/ubuntu-18.04-desktop-amd64"
    ubuntu.vm.provision :shell, :path => "provision.sh", :privileged => false
    ubuntu.vm.network "private_network", ip: "10.20.30.40"
    ubuntu.vm.synced_folder "host-share", "/home/vagrant/host-share"
    ubuntu.vm.box_check_update = false

    ubuntu.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
        vb.customize ["modifyvm", :id, "--usb", "on"]   
        vb.gui = true
    end

    ubuntu.vm.network "public_network", bridge: "Default Switch"

    ubuntu.vm.provider "parallels" do |prl|
        prl.update_guest_tools = true
    end
  end

  config.vm.define "win10" do |win10|
    win10.vm.box = "universalvishwa/windows-10-professional-x64"

    win10.vm.synced_folder "host-share", "c:\\host-share"
    win10.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
      vb.customize ["modifyvm", :id, "--usb", "on"]    
#      vb.customize ["modifyvm", :id, "--usbxhci", "off"]
      vb.customize ["modifyvm", :id, "--monitorcount", "1"]   
      vb.gui = true
    end
  end
end
