# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "peru/ubuntu-18.04-desktop-amd64"
    ubuntu.vm.provision :shell, :path => "provision.sh", :privileged => false
    ubuntu.vm.network "private_network", ip: "10.20.30.40"
    ubuntu.vm.synced_folder "host-share", "/home/vagrant/host-share"
    ubuntu.vm.box_check_update = false

    ubuntu.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
        vb.customize ["modifyvm", :id, "--usb", "on"]   
        vb.gui = true
    end

    ubuntu.vm.network "public_network", bridge: "Default Switch"

    ubuntu.vm.provider "parallels" do |prl|
        prl.update_guest_tools = true
    end
  end

#TODO, not finished and not working correctly. I can restore the box atm.
  config.vm.define "win10" do |win10|
    win10.vm.box = "win10"
    win10.vm.guest = :windows
    win10.vm.communicator = "winrm"
    win10.vm.boot_timeout = 600
    win10.vm.graceful_halt_timeout = 600

    #win10.vm.synced_folder "host-share", "C:\\host-share"

    win10.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
        vb.customize ["modifyvm", :id, "--usb", "on"]   
        vb.customize ["modifyvm", :id, "--nictype1", "82540EM"]
        vb.gui = true
    end


    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    win10.vm.network :forwarded_port, guest: 3389, host: 33899, id: "rdp", auto_correct: true
    win10.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  
    # config.vm.provider "virtualbox" do |vb|
    #    # Customize the name of VM in VirtualBox manager UI:
    #    vb.name = "yourcompany-yourbox"
    # end
  end
end
